### ISSUE TITLE
Bulk insert fails when database contains computed columns

### ISSUE THREAD

**Issue by InteXX** [mtanneryd/ef6-bulk-operations#12]
I'm getting errors when attempting to insert into a table that contains computed columns. In this case, `Shift` is a computed column.

Is there a way to 'ignore' these columns for the purpose of the insert?

    Unhandled Exception: System.Data.SqlClient.SqlException: Cannot insert the value NULL into column 'Shift', table 'tempdb.dbo.#8e9dd922f00c4719b21059e9c4042ccf___________________________________________________________________________________000000000009'; column does not allow nulls. INSERT fails.
    The statement has been terminated.
       at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
       at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
       at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
       at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
       at System.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
       at System.Data.SqlClient.SqlBulkCopy.RunParser(BulkCopySimpleResultSet bulkCopyHandler)
       at System.Data.SqlClient.SqlBulkCopy.CopyBatchesAsyncContinuedOnSuccess(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)
       at System.Data.SqlClient.SqlBulkCopy.CopyBatchesAsyncContinued(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)
       at System.Data.SqlClient.SqlBulkCopy.CopyBatchesAsync(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)
       at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestContinuedAsync(BulkCopySimpleResultSet internalResults, CancellationToken cts, TaskCompletionSource`1 source)
       at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestAsync(CancellationToken cts, TaskCompletionSource`1 source)
       at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalAsync(CancellationToken ctoken)
       at System.Data.SqlClient.SqlBulkCopy.WriteRowSourceToServerAsync(Int32 columnCount, CancellationToken ctoken)
       at System.Data.SqlClient.SqlBulkCopy.WriteToServer(IDataReader reader)
       at Tanneryd.BulkOperations.EF6.DbContextExtensions.DoBulkCopy(DbContext ctx, IList entities, Type t, Mappings mappings, SqlTransaction transaction, Boolean allowNotNullSelfReferences, TimeSpan commandTimeout, BulkInsertResponse response)
       at Tanneryd.BulkOperations.EF6.DbContextExtensions.DoBulkInsertAll(DbContext ctx, IList`1 entities, SqlTransaction transaction, Boolean recursive, Boolean allowNotNullSelfReferences, TimeSpan commandTimeout, Dictionary`2 savedEntities, BulkInsertResponse response)
       at Tanneryd.BulkOperations.EF6.DbContextExtensions.BulkInsertAll[T](DbContext ctx, BulkInsertRequest`1 request)
       at Tanneryd.BulkOperations.EF6.DbContextExtensions.BulkInsertAll[T](DbContext ctx, IList`1 entities, SqlTransaction transaction, Boolean recursive)
       at DataMigrator.Main.Migrate() in D:\Dev\DataMigrator\Modules\Main.vb:line 47
       at DataMigrator.Main.Main() in D:\Dev\DataMigrator\Modules\Main.vb:line 5

**Comment by InteXX** [comment]
That's great, thanks.

**Comment by mtanneryd** [comment]
Ok. I have replicated the bug and will fix it asap. Might be a day or two though since I am currently under the dire influence of the flu. (pun intended) :-)

**Comment by mtanneryd** [comment]
There is a potential fix ready now available in 1.2.3-beta1. Please try it out and let me know how if it works for you. This beta version also contains some, not fully tested, fixes for problems with many-to-many relationship inserts.

**Comment by InteXX** [comment]
[D<sup>3</sup>](https://www.amazon.com/dp/B00GB85JR4/) + [Iodine](http://www.thyroidnascentiodine.com/). I've been at it daily for four years, and I haven't been down once. Get well  :-)

Alas, the problem persists.

    <?xml version="1.0" encoding="utf-8"?>
    <packages>
      <package id="AutoMapper" version="8.0.0" targetFramework="net472" />
      <package id="EntityFramework" version="6.2.0" targetFramework="net472" />
      <package id="Intexx.ServiceModel" version="2017.12.1.1" targetFramework="net472" />
      <package id="System.ValueTuple" version="4.5.0" targetFramework="net472" />
      <package id="Tanneryd.BulkOperations.EF6" version="1.2.3-beta1" targetFramework="net472" />
    </packages>

Here's the SQL statement I'm using to create the `Shift` computed column:

    ALTER TABLE [LogEntries] ADD [Shift] AS (IIF(DATEPART(HOUR, DATEADD(HOUR, -7, [LogTime])) < 12, 1, 2)) PERSISTED

Is there anything further I can do to help? (I'm not a C#; been a VB since '99.)

**Comment by mtanneryd** [comment]
Hi!

It would be helpful if you could show me how you have configured your context. Fluent API? Attributes?

**Comment by mtanneryd** [comment]
It seems to me as if you are simply "ignoring" your computed columns in your fluent config. Is this correct? If so, that is probably why it does not work. Unless you configure the computed columns as such EF will think that they are regular columns and try to treat them accordingly. 

You need something like this

modelBuilder.Entity(Of LogEntry)()
.Property(Function(t) t.Shift)
.HasDatabaseGeneratedOption(DatabaseGeneratedOption.Computed)

**Comment by InteXX** [comment]
Yes, I tried that first.

But I ran into [this problem](https://stackoverflow.com/a/50152464/722393).

**Comment by mtanneryd** [comment]
No such insight unfortunatly but there is a new beta release 1.2.3-beta2
available in a couple of minutes that might help with your initial problem.

/Måns

Måns Tånneryd
Tånneryd IT AB
Barrskogsvägen 19
186 53 Vallentuna
+46-705140093
https://se.linkedin.com/in/manstanneryd
https://www.facebook.com/matkollen



Den ons 16 jan. 2019 kl 04:04 skrev InteXX <notifications@github.com>:

**Comment by InteXX** [comment]
That was quite a bit of work you did for `1.2.3-beta1`, followed up with a simple SQL statement fix for `1.2.3-beta2`  :-)

So I'm pleased to be able to report that it works.

I was just about to junk my computed columns and retool for a view, but then your `beta2` came along and saved the day. It's as easy as 1-2-3  ;-)

Good job. Thanks  :-)

I'm curious... have you tested this with SQLCE?

**Comment by mtanneryd** [comment]
No. Have not had the time to test with anything else than SQL Server and LocalDb. Also plan to make a version available for EF Core but it will take a while. Lots on the agenda at the moment.

**Comment by InteXX** [comment]
I understand. I'll give it a try.
